name: Run Tests
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore TudoMario.sln
 
    - name: Build Solution
      run: msbuild TudoMario.sln /p:Configuration=Debug /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:AppxBundlePlatforms="x86" /p:AppxPackageDir=".\AppxPackages" /p:AppxBundle=Always
 
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1
      
    - name: Run Tests
      id: testing
      run: vstest.console.exe /Platform:x86 TudoMarioTests\bin\x86\Debug\TudoMarioTests.build.appxrecipe > testresult.txt
      continue-on-error: true
      
    - name: Print out Directory Structure
      run: ls -R
 
    - uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: testresult.txt

  test:
    needs: [build]
    runs-on: windows-latest
    steps:
    - name: Read artifact
      uses: actions/download-artifact@v2
      with:
        name: test-results
    
    - name: Print out Log File
      run: cat *.trx
