name: Run Tests
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore TudoMario.sln
 
    - name: Build Solution
      run: msbuild TudoMario.sln /t:TudoMario /t:TudoMarioTests /p:Configuration=Debug /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:AppxBundlePlatforms="x86" /p:AppxPackageDir=".\AppxPackages" /p:AppxBundle=Always
          
    - name: Logging workdir
      run: pwd
      
    - name: Recursive ls
      run: ls -R
      
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1
      
    - name: VSTest
      #run: vstest.console.exe /Platform:x86 TudoMarioTests\obj\x86\Debug\TudoMarioTests_1.0.0.0_Bundle\TudoMarioTests_1.0.0.0_x86_Debug.appx
      run: vstest.console.exe /Platform:x86 TudoMarioTests\obj\x86\Debug\TudoMarioTests.build.appxrecipe
    #- name: Ls of Core
      #run: ls .\TudoMarioTests\bin\x86\Debug\Core\
 
    #- name: Run Tests
      #run: '& "$(vswhere -property installationPath)\Common7\IDE\MSTest.exe" .\TudoMarioTests\bin\x86\Debug\Core\TudoMarioTests.exe'
 
    #- name: Upload Artifact
      #uses: actions/upload-artifact@v1.0.0
      #with:
        #name: published_app
        #path: bin\Release\Publish
